### ISSUE TITLE
[BUG] Error when loading the session-based model in example

### ISSUE THREAD

**Issue by FredHJC** [NVIDIA-Merlin/models#908] opened 2022-11-30 19:02 UTC
# ❓ Questions & Help

## Details

https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb

We are trying to implement the session-based models shown in the above notebook. However, there is a consistent error when loading the saved model. `TypeError: ('Keyword argument not understood:', 'layer was saved without config')`

We can just run the example notebook and save the trained model. Then the error occurs when trying to load it. It looks like customized layers / prediction tasks should be handled with a manually specified config.

<img width="835" alt="Screen Shot 2022-11-30 at 1 59 41 PM" src="https://user-images.githubusercontent.com/24794992/204885225-48809ea7-b1e8-4b88-84ee-851584ee1800.png">

**Comment by zhiruiwang** [comment] 2022-12-01 03:46
### Steps/Code to reproduce bug

1. Run the [Dressipi notebook](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb) Transformer-based model example after the model is trained:  
```
model_transformer.fit(loader, 
                      validation_data=val_loader,
                      epochs=EPOCHS
                     )
```
2. Save the model to disk, which is successful:
```
model_transformer.save(os.path.join('/ecom_modeling/11-30-session', 'transformer'))
```
It does have some warnings though:
```
WARNING:tensorflow:Skipping full serialization of Keras layer TFSharedEmbeddings(
  (_feature_shapes): Dict(
    (f_47_list_seq): TensorShape([1024, None])
    (f_68_list_seq): TensorShape([1024, None])
    (item_id_list_seq): TensorShape([1024, None])
    (item_id_last): TensorShape([1024, 1])
  )
  (_feature_dtypes): Dict(
    (f_47_list_seq): tf.int32
    (f_68_list_seq): tf.int32
    (item_id_list_seq): tf.int32
    (item_id_last): tf.int32
  )
), because it is not built.
.......
INFO:tensorflow:Unsupported signature for serialization: ((Prediction(outputs={'purchase_id_first/categorical_output': TensorSpec(shape=(None, 23272), dtype=tf.float32, name='outputs/outputs/purchase_id_first/categorical_output')}, targets={'purchase_id_first/categorical_output': TensorSpec(shape=(None, 23272), dtype=tf.float32, name='outputs/targets/purchase_id_first/categorical_output')}, sample_weight={'purchase_id_first/categorical_output': None}, features=None, negative_candidate_ids=None), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7fb613ff95e0>), {}).
```
3. Load the model from disk, which causes the error:
```
model_loaded = tf.keras.models.load_model(
        os.path.join('/ecom_modeling/11-30-session', 'transformer'))
```

```
TypeError: ('Keyword argument not understood:', 'layer was saved without config')
```

We are wondering if we did something wrong with the saving and loading of the model, or if there's a bug in saving and loading Merlin session-based models.

Also not sure if it's related to https://github.com/NVIDIA-Merlin/models/issues/898 or https://github.com/NVIDIA-Merlin/models/issues/889

**Comment by sararb** [comment] 2022-12-19 18:39
Thank you for reporting the bug. 

I was able to reproduce this error when loading the model without importing `merlin.models.tf`.  In fact, the custom layers will not be understood by Tensorflow if Merlin Models (MM) is not imported. 

The recommended way to load a trained MM model is to import merlin.models.tf before calling `tf.keras.models.load_model`, as follows:

```
import tensorflow as tf
import merlin.models.tf as mm
model = tf.keras.models.load_model('transformer-model')
```

Please let us know if this fixes the loading issue. Thanks!

**Comment by oliverholworthy** [comment] 2022-12-19 18:46
We also have a classmethod on our Model class. So can also do the following to load the model

```python
import merlin.models.tf as mm

mm.Model.load('<path-to-saved-model-directory>')
```

**Comment by rnyak** [comment] 2023-01-05 14:58
@zhiruiwang @FredHJC closing this issue since it should be solved via https://github.com/NVIDIA-Merlin/models/pull/927.

**Closed by rnyak** 2023-01-05 14:58 UTC
Labels: bug, status/needs-triage, P0

**Comment by zhiruiwang** [comment] 2023-01-11 20:24
@rnyak We used the Merlin-tensorflow 22.12 image and refactored our pipeline to use the lastest API of merlin-models codebase, now the saving and loading two tower, LSTM, and transformer models are all working. Thanks for the help!
