### ISSUE TITLE
[BUG] DLRM training using pretrained embeddings failing due to tuple shape mismatch between the passed embedding's unique number of items and nvtabular workflow's unique number of items

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/models#609] opened 2022-07-26 23:47 UTC
### Bug description

nvtabular workflow schema computes more unique number of items than in the training data which in turn leads to invalid argument error when trying to fit the model with pretrained embeddings.

### Steps/Code to reproduce bug

1. Please download the sample data and notebooks [from the link](https://drive.google.com/drive/u/1/folders/1IK-2P6SqkdT-sxDUn0PRmprih2xNQXOa)
2. `01-Building-Recommender-Systems-with-Merlin.ipynb` should give more details of the error in cell 27.

### Environment details
- Merlin version: 22.05
- Tensorflow version (GPU?): 2.9.1
![Screen Shot 2022-07-25 at 2 55 18 PM](https://user-images.githubusercontent.com/28987826/181131071-34eb1226-0206-4e1d-b86f-963977332818.png)
![Screen Shot 2022-07-25 at 2 55 39 PM](https://user-images.githubusercontent.com/28987826/181131079-252a23ef-6b8b-400b-9539-2337a76bb372.png)
![Screen Shot 2022-07-25 at 2 56 47 PM](https://user-images.githubusercontent.com/28987826/181131081-35dca01c-4ef6-4c20-a0f1-ede408d8805b.png)
![Screen Shot 2022-07-25 at 2 57 27 PM](https://user-images.githubusercontent.com/28987826/181131082-3dd260e6-035c-47ee-a0f4-1369edd15b52.png)
<img width="636" alt="Screen Shot 2022-07-25 at 4 12 52 PM" src="https://user-images.githubusercontent.com/28987826/181131083-e5c77cb5-d92a-4929-9ae1-fa0ee595bbb4.png">
<img width="598" alt="Screen Shot 2022-07-25 at 4 13 10 PM" src="https://user-images.githubusercontent.com/28987826/181131084-6cdb5f0a-50d2-4c18-9033-2e7026cf3f21.png">

**Comment by EvenOldridge** [comment] 2022-07-29 23:58
Merlin categorify op always holds out the zero position for null values, even if none exist within the dataset.  I'm guessing this is causing issues with Merlin Models when it's trying to create the embeddings from pretrained.

@marcromeyn @sararb any ideas for how to correct this?

**Comment by rnyak** [comment] 2022-08-03 14:41
@EvenOldridge @mkumari-ed this is not a bug in Merlin models. The error is because Mamta is adding pre-trained embeddings to her model for a given column, and most likely she is also categorifying the column in the NVT pipeline, which she should not do that way.  When she categorifies that column, Merlin models creates an embedding table for this column, and its dimensions do not match with the ones that she feeds via `TensorInilializer`. We have workaround solution to use TensorInilializer class but I'd recommend to wait for the high level API example.

**Comment by mkumari-ed** [comment] 2022-08-03 16:10
Hi Ronay and Even,

Just a bit of correction to what you mentioned below. I am not
categorifying the column for which the pretrained embeddings is added in
the model training.

Thanks for sharing your thoughts. I can wait for the high level API example
as you suggested. But I wanted to first understand why the schema shows 2
more unique number of items than what is there in the dataset.

-Mamta

**Comment by rnyak** [comment] 2022-08-03 16:55
@mkumari-ed thanks for the content. schema shows +1 for the embedding dimension because it is reserving an embedding representation for the out of vocabulary or null values (those are mapped to 0 after the NVTabular processing ) in the train and val set . That's expected. Hope that helps.

So that's not the cause of your problem here.  Some steps required to make this work and I think you do not do these steps, that's why you get this error:

- you need to create a mapping column (consists of integer values) for this  `embeddin_st1` column so that an embedding lookup can be done. Most likely this should be done in the preprocessing step before NVT pipeline.
- you need to tag this new mapped column as categorical column but should not categorify it.
-  since you do not categorify this new column, but still want embedding table to be created you need to hack the schema file so that you can add this new column and its properties in the schema.
- you need to create a dictionary with all the features and  corresponding emb dimensions for each categ col, and this dictionary should be also fed to DLRM model block 
- you need to make the corresponding embedding layers frozen., i.e., trainable=False.

**Comment by sohn21c** [comment] 2022-08-03 20:02
re: "But I wanted to first understand why the schema shows **2 more** unique number of items than what is there in the dataset."
>> @mkumari-ed, will you please confirm whether it is **1 more unique item or 2 more?** Provided screenshots show that the embedding dimension is (26033, 768) and the processed cardinality is 26034, which makes it 1 more unique item.

Also, let's close this bug if the raised issue/question (larger cardinality in NVTabular schema) was answered by the comment from Even and Ronay (NVT reserves zero position for null values). I suggest that @mkumari-ed create a new issue/question re: using pre-trained embeddings w/ relevant title and description and @rnyak to add comments there for OP to try.

**Comment by mkumari-ed** [comment] 2022-08-03 21:46
@sohn21c schema shows 1 more item than the data but the error I attached at the time of training shows 2 more items.

**Comment by mkumari-ed** [comment] 2022-08-03 21:49
@rnyak  Thanks for the detailed explanation. 1 & 2 pointers makes full sense to me. Points 3-5 makes sense if I read it high-level but I am not quite sure how these steps are done so an example would be great help. Is it safe to assume that the high-level API example that is in progress will have these steps included?

**Comment by rnyak** [comment] 2022-08-04 20:03
@mkumari-ed I will look into `training shows 2 more items.`. thanks.

**Comment by rnyak** [comment] 2022-08-16 17:21
@mkumari-ed please check out this [example] (https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/entertainment-with-pretrained-embeddings.ipynb).  This will give you an idea how to use pre-trained embeddings. You will need the latest main branch from `models`  and `NVT` library. I'd recommend to wait for the `22.08` release.

**Comment by viswa-nvidia** [comment] 2022-08-16 17:22
Priority increased to P0

**Closed** 2022-08-17 16:07 UTC
Labels: question, P0
